packages:
  - 'common'
  - 'common-ui'
  - 'client'
  - 'hall-of-fame'
  - 'server'
  - 'tests'
allowBuilds:
  esbuild: false
  unrs-resolver: false
blockExoticSubdeps: true

minimumReleaseAge: 10080
