@server = http://localhost:4400
###
POST {{server}}/register
Content-Type: application/json

{
  "username": "nagarian",
  "password": "azerty123",
  "team": "h4ck3rs"
}
###
POST {{server}}/login
Content-Type: application/json

{
  "username": "nagarian",
  "password": "azerty123"
}
###
POST {{server}}/logout
###
GET {{server}}/api/ctftime/team
###
GET {{server}}/api/ctftime/capture
###
@challengeId = 682f16ba8a20280c8f789b31
@adminChallengeApiKey = 519505d9-a171-4d82-8904-d4183ce5c84a
#
GET {{server}}/api/admin/challenges/{{challengeId}}/team-tokens
x-api-key: {{adminChallengeApiKey}}
###
